
config = {
    "ranks": {
        "KAITEI": None,
        "SHATEI": ["SHATEI YORI TAKAI", "SHATEI CHUKYU"],
        "KYODAI": ["KYODAI CHUKYU", "KYODAI O TOSHIYORI", "KYODAI YORI TAKAI", "KYODAI ZENPAN TEKI", "KYODAI SAIKO"],
        "SHATEIGASHIRA": None,
        "WAKAGASHIRA": ["WAKAGASHIRA SAIKO"]
    },
    "commands": {
        "rank_up": {
            "bot_answers": [
                "**{} HA ALCANZADO EL RANGO DE {}! TU DEDICACIÓN Y LEALTAD SON EJEMPLOS DE HONOR Y CORAJE. OMEDETO (FELICIDADES).**",
                "**¡OMEDETO (FELICIDADES) {}! HAS SIDO ASCENDIDO A {}, TU DISCIPLINA Y HONOR BRILLAN.**",
                "**¡{}! HAS LOGRADO EL RANGO DE {}. KEIGA (ENHORABUENA), TU COMPROMISO REFLEJA LA VERDADERA DIGNIDAD.**",
                "**¡SUGOI (INCREÍBLE), {}! AHORA ERES {}, TU VALOR Y ARTE DE LUCHA SON DIGNOS DE ALABANZA.**",
                "**¡{}! OMEDETO (FELICIDADES) POR TU ASCENSO A {}. TU INTEGRIDAD TE HA LLEVADO A ESTE HONOR.**",
                "**¡¿NANI?!, ¡{}, TE HAS GANADO EL RANGO DE {}!. TU SABIDURÍA Y LEALTAD SON AHORA UN EJEMPLO A SEGUIR.**",
                "**¡OMEDETO (FELICIDADES) {}! AHORA ERES {}, TU PERSEVERANCIA EN LA BÚSQUEDA DE LA VERDAD ES INSPIRADORA.**",
                "**SUBARASHII (MAGNÍFICO), {}. TU ASCENSO A {} ES TESTIMONIO DE TU GRAN HONOR Y COMPROMISO. SIGUE ASÍ.**"
            ]
        },
        "rank_down": {
            "bot_answers": [
                "**{}, GANBATTE (ESFUÉRZATE). DESAFORTUNADAMENTE HAS SIDO DEGRADADO A {}. TU HUMILDAD Y RESILIENCIA TE PERMITIRÁN SUPERAR ESTO.**",
                "**¡{}! AHORA ERES {}, PERO TU VALOR Y HONOR SIGUEN SIENDO NUESTRO EJEMPLO. REAFIRMA TU COMPROMISO. GANBARE (ÁNIMO).**",
                "**¡MOSHIWAKE ARIMASEN (MIS MÁS SINCERAS DISCULPAS), {}! AHORA ERES {}, PERO TU DEDICACIÓN Y FUERZA TE PERMITIRÁN RECUPERAR TU HONOR. SIGUE ADELANTE.**",
                "**GANBARE (ÁNIMO), {}. HAS SIDO DEGRADADO A {}. TUS ACCIONES REFLEJARÁN TU VERDADERA FUERZA Y HONOR EN ESTE CAMBIO.**",
                "**¡{}! HAS BAJADO A {}, PERO LA VERDADERA FUERZA SE MUESTRA EN LA ADVERSIDAD. SIGUE ADELANTE.**",
                "**{} HA SIDO DEGRADADO A {}. PERO TU ESPÍRITU Y HONOR TE LLEVARÁN A SUPERAR CUALQUIER PRUEBA. GANBATTE (ESFUÉRZATE).**",
                "**¡SHITSUREI SHIMASHITA (PERDÓN POR LA MOLESTIA), {}! AHORA ERES {}, PERO LA VERDADERA GRANDEZA SE MANIFIESTA EN LA SUPERACIÓN DE RETOS.**",
                "**¡{}! TU DESCENSO A {} ES UNA OPORTUNIDAD PARA REAFIRMAR TU HONOR Y DISCIPLINA. SIGUE ADELANTE. GANBARE (ÁNIMO).**"            ]
        }
    }
}