
config = {
    "commands": {
        "rank_up": {
            "bot_answers": [
                "**{} HA ALCANZADO EL RANGO DE {}! TU DEDICACIÓN Y LEALTAD SON EJEMPLOS DE HONOR Y CORAGE.**",
                "**¡FELICIDADES {}! HAS SIDO ASCENDIDO A {}, TU DISCIPLINA Y HONOR BRILLAN.**",
                "**¡ENHORABUENA, {}! HAS LOGRADO EL RANGO DE {}. TU COMPROMISO REFLEJA LA VERDADERA DIGNIDAD.**",
                "**¡EXCELENTE, {}! AHORA ERES {}, TU VALOR Y ARTE DE LUCHA SON DIGNOS DE ALABANZA.**",
                "**¡{}! FELICIDADES POR TU ASCENSO A {}. TU INTEGRIDAD TE HA LLEVADO A ESTE HONOR.**",
                "**¡BRAVO, {}! HAS GANADO EL RANGO DE {}. TU SABIDURÍA Y LEALTAD SON UN EJEMPLO A SEGUIR.**",
                "**¡{}! TU ASCENSO A {} REFLEJA TU INQUEBRANTABLE DEDICACIÓN Y HONOR. CONTINÚA SIENDO UN EJEMPLO.**",
                "**¡FELICIDADES {}! AHORA ERES {}, TU PERSEVERANCIA EN LA BÚSQUEDA DE LA VERDAD ES INSPIRADORA.**",
                "**¡{}! HAS ALCANZADO EL NIVEL DE {}. TU VALOR Y LEALTAD REFLEJAN TU ESPÍRITU.**",
                "**¡QUÉ LOGRO, {}! TU ASCENSO A {} ES TESTIMONIO DE TU GRAN HONOR Y COMPROMISO. SIGUE ADELANTE.**"
            ]
        },
        "rank_down": {
            "bot_answers": [
                "**{} DESAFORTUNADAMENTE HA SIDO DEGRADADO A {}. TU HUMILDAD Y RESILIENCIA TE PERMITIRÁN SUPERAR ESTO.**",
                "**¡{}! AHORA ERES {}, PERO TU VALOR Y HONOR SIGUEN SIENDO NUESTRO EJEMPLO. REAFIRMA TU COMPROMISO.**",
                "**¡{}! EL CAMBIO A {} ES UNA OPORTUNIDAD PARA REFLEJAR Y CRECER. TU HONOR NO SE VE DIFICULTADO.**",
                "**¡LO SIENTO, {}! AHORA ERES {}, PERO TU DEDICACIÓN Y FUERZA TE PERMITIRÁN RECUPERAR TU HONOR.**",
                "**{} HAS SIDO DEGRADADO A {}. TUS ACCIONES REFLEJARÁN TU VERDADERA FUERZA Y HONOR EN ESTE CAMBIO.**",
                "**¡{}! HAS BAJADO A {}, PERO LA VERDADERA FUERZA SE MUESTRA EN LA ADVERSIDAD. CONTINÚA ADELANTE.**",
                "**{} HA SIDO DEGRADADO A {}. PERO TU ESPÍRITU Y HONOR TE LLEVARÁN A SUPERAR CUALQUIER PRUEBA.**",
                "**¡{}! AHORA ERES {}, PERO LA VERDADERA GRANDEZA SE MANIFIESTA EN LA SUPERACIÓN DE RETOS.**",
                "**¡{}! TU DESCENSO A {} ES UNA OPORTUNIDAD PARA REAFIRMAR TU HONOR Y DISCIPLINA. SIGUE ADELANTE.**",
                "**{} HA SIDO REBAJADO AL RANGO DE {}. MANTEN TU HONOR Y FUERZA AUN EN ESTA NUEVA POSICIÓN.**"
            ]
        }
    }
}